FROM ruby:2.6.2-alpine as build
RUN apk --no-cache add build-base tzdata sqlite sqlite-dev postgresql-dev yarn nodejs-current imagemagick && gem install tzinfo-data
WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
COPY . /app
RUN yarn install --check-files
RUN bin/rake assets:precompile
CMD bundle exec rails db:migrate && bundle exec rails s -p 3000 -b 0.0.0.0
