name: Publish Docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Production Container
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: malaber/condolence_book
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true

      - name: Publish Development Container
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: malaber/condolence_book_dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true
          dockerfile: Dockerfile.dev